title: De Sistemas
language: "es_AR"
og_image: "/assets/img/og_image.webp"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Blog sobre desarrollo y arquitectura de software, homelabing, redes y sistemas.
baseurl: ""
url: ""
collections:
  pages:
    output: true
    permalink: /:path/
  store:
    output: true   # Cada producto tendrá su propia URL
    permalink: /tienda/:name/
  announcements:
    output: true   # Cada producto tendrá su propia URL
    permalink: /adelantos/:name/

markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed